version: '3.7'
services:
# home assistant user (www-data) 33:33
  homeassistant:
    container_name: ha-homeassistant
    image: homeassistant/home-assistant:latest
    volumes:
      - type: volume
        source: haconfig
        target: /config
      - type: bind
        source: /etc/localtime
        target: /etc/localtime
        read_only: true
      - type: bind
        source: ./wait-for-it.sh
        target: /wait-for-it.sh
        read_only: true
      - type: bind
        source: ./gosu
        target: /gosu
      - type: bind
        source: ./homeassistant/entrypoint.sh
        target: /entrypoint.sh
        read_only: true
    restart: always
    entrypoint:
      - /entrypoint.sh
    networks:
      - frontend
      - backend
    secrets:
      - source: ha-secrets
        target: /config/secrets.yaml
        mode: 0440
        uid: '33'
        gid: '33'
    expose:
      - '8123/tcp'
    depends_on:
      - mariadb
      - mosquitto
# mysql user 999:999
  mariadb:
    container_name: ha-mariadb
    image: mariadb:latest
    restart: always
    volumes: 
      - type: volume
        source: mariadb-data
        target: /var/lib/mysql
      - type: bind
        source: ./mariadb/chmodtmp-thenenter.sh
        target: /chmodtmp-thenenter.sh
        read_only: true
    networks:
      - backend
    secrets:
      - source: ha-mysql-user
        target: MYSQL_USER
        mode: 0440
        uid: '999'
        gid: '999'
      - source: ha-mysql-password
        target: MYSQL_PASSWORD
        mode: 0440
        uid: '999'
        gid: '999'
      - source: ha-mysql-database
        target: MYSQL_DATABASE
        mode: 0440
        uid: '999'
        gid: '999'
    entrypoint:
      - /chmodtmp-thenenter.sh
    environment:
      MYSQL_RANDOM_ROOT_PASSWORD: 'yes'
      MYSQL_USER_FILE: /run/secrets/MYSQL_USER
      MYSQL_PASSWORD_FILE: /run/secrets/MYSQL_PASSWORD
      MYSQL_DATABASE_FILE: /run/secrets/MYSQL_DATABASE
    expose:
      - '3306/tcp'
# mosquitto user 100:101 
  mosquitto:
    container_name: ha-mosquitto
    image: eclipse-mosquitto:latest
    restart: always
    volumes:
      - type: volume
        source: mosquitto-data
        target: /mosquitto/data
      - type: volume
        source: mosquitto-log
        target: /mosquitto/log
      - type: bind
        source: ./mosquitto/bootstraplogins.sh
        target: /bootstraplogins.sh
        read_only: true
    secrets:
      - source: ha-mosquitto-logins
        target: mosquitto-logins
        mode: 0440
    entrypoint:
      - /bootstraplogins.sh
    networks:
      - frontend
    ports:
      - 8883:8883/tcp
    expose:
      - '1883/tcp'
# nginx user 101:101
  nginx:
    image: nginx:latest
    container_name: ha-nginx
    volumes:
      - type: volume
        source: letsencrypt-data
        target: /etc/letsencrypt
      - type: volume
        source: letsencrypt-challenge
        target: /data/letsencrypt
    restart: always
    configs:
      - source: ha-nginx-default-notls
        target: /etc/nginx/conf.d/default.conf
        mode: 0444
      - source: ha-nginx-nginx
        target: /etc/nginx/nginx.conf
        mode: 0444
    ports:
      - 443:443/tcp
      - 80:80/tcp
    depends_on:
      - homeassistant
    networks:
      - frontend
    secrets:
      - source: ha-nginx-dhparm
        target: dhparm-2048.pem
        mode: 0440
        uid: '101'
        gid: '101'

configs:
  ha-nginx-default-notls:
    file: ./nginx/default-notls.conf
  ha-nginx-default:
    file: ./nginx/default.conf
  ha-nginx-nginx:
    file: ./nginx/nginx.conf

networks:
  frontend:
  backend:
    internal: true

volumes:
# mariadb data volume
  mariadb-data:
# home assistant config
  haconfig:
# mosquitto data/log
  mosquitto-data:
  mosquitto-log:
# letsencrypt
  letsencrypt-data:
  letsencrypt-challenge:

secrets:
# Secrets for mariadb
  ha-mysql-user:
    external: true
  ha-mysql-password:
    external: true
  ha-mysql-database:
    external: true
# Secrets.yaml file for homeassistant 
  ha-secrets:
    external: true
# nginx secrets
  ha-nginx-dhparm:
    external: true
# mosquitto logins
  ha-mosquitto-logins:
    external: true
